name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test ECR Login Token
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build -t ai-image-detector:$IMAGE_TAG .
        docker tag ai-image-detector:$IMAGE_TAG ${{ steps.ecr-login.outputs.registry }}/ai-image-detector:$IMAGE_TAG

    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=$(date +%s)
        docker push ${{ steps.ecr-login.outputs.registry }}/ai-image-detector:$IMAGE_TAG

    - name: Output pushed image URI
      run: |
        echo "Image pushed: ${{ steps.ecr-login.outputs.registry }}/ai-image-detector:$IMAGE_TAG"
